#!/bin/sh
#
# Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -e

PROGNAME="`basename $0`"
VERSION='v1.0'

_PATH_MAN_CONF=/etc/man.conf

usage() {
        echo "usage: $PROGNAME [-d] [-s section] utility"
}

version() {
        echo "$PROGNAME $VERSION"
}

section="_default"

while getopts "ds:" opt;do
	case $opt in
		d) set -x;;
		s) section="$OPTARG";;
		*) usage; exit 1;;	# NOTREACHED
		:) echo "$PROGNAME: option requires an argument -- $OPTARG";
		   usage; exit 1;;	# NOTREACHED
		?) echo "$PROGNAME: unkown option -- $OPTARG";
		   usage; exit 1;;	# NOTREACHED
	esac
done
shift $(( $OPTIND -1 ))

if [ -z "$1" ]; then
	usage
	exit 1
else
	utility="$1"
	shift
fi

if [ $# -ge 1 ]; then
	echo "$PROGNAME: invalid trailing chars -- $@"
	usage
	exit 1
fi

paths=`cat $_PATH_MAN_CONF | grep "^$section" | cut -f2-`
subdirs=`cat $_PATH_MAN_CONF | grep "^_subdir" | cut -f2-`

if [ "$PROGNAME" = "renv" ]; then
	target=".Ev"
else
	target=".Xr"
fi

# List every valid directory
for dir in $paths; do
	if [ "$dir" != "${dir%/}" ] ;then
		for subdir in $subdirs; do
			[ -d $dir$subdir ] && echo $dir$subdir
		done
	else
		[ -d $dir ] && echo $dir
	fi
done | while read; do
	for file in `ls $REPLY`; do
		if grep "$target $utility" $REPLY/$file > /dev/null; then
			echo $file | tr '.' ' '
		fi
	done
done
